# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: detect-private-key

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint
        language: system
        files: \.(js|jsx|ts|tsx)$
        args: ['--fix']
        pass_filenames: true
        exclude: '^tests/'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, yaml, markdown]
        exclude: '^(dist|build)/'
        args: ['--write']

  - repo: local
    hooks:
      - id: npm-test
        name: npm test
        entry: npm test
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]

      - id: npm-build
        name: npm build
        entry: npm run build
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]

      - id: typescript-check
        name: TypeScript type check
        entry: npx tsc --noEmit
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]
