name: Generate Coverage Badge

on:
  push:
    branches: [ main, missing-tests ]

jobs:
  coverage-badge:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests with coverage
      run: npm test -- --coverage --coverageReporters=json-summary
      env:
        NODE_ENV: test

    - name: Extract coverage percentage
      run: |
        COVERAGE=$(cat coverage/coverage-summary.json | jq -r '.total.statements.pct')
        echo "COVERAGE_PERCENTAGE=$COVERAGE" >> $GITHUB_ENV

    - name: Extract coverage percentage
      run: |
        COVERAGE=$(cat coverage/coverage-summary.json | jq -r '.total.statements.pct')
        echo "COVERAGE_PERCENTAGE=$COVERAGE" >> $GITHUB_ENV

    - name: Generate Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: YOUR_GIST_ID # Replace with actual gist ID
        filename: mcp-socialmedia-coverage.json
        label: Coverage
        message: ${{ env.COVERAGE_PERCENTAGE }}%
        valColorRange: ${{ env.COVERAGE_PERCENTAGE }}
        maxColorRange: 100
        minColorRange: 0
